server:
  port: '8080'
spring:
  jpa:
    properties:
      hibernate:
        schema_update:
          unique_constraint_strategy: RECREATE_QUIETLY
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  datasource:
    password: 839841413f5d655193dacfc759f63b8989e0b4a7f0812e1f8b91a0cad6e88f4a
    driver-class-name: org.postgresql.Driver
    username: zahlzwisiamtzt
    url: jdbc:postgresql://ec2-52-30-159-47.eu-west-1.compute.amazonaws.com:5432/dcf53027p75359
jwt:
  expiration-time: '1800000'
  secret: itransition
  type: Bearer
  header:
    name: json-web-token
  refresh:
    expiration-time: '10800000'
cors:
  allowed-origins: http://localhost:3000
  allowed-methods: '*'
  allow-credentials: 'true'
  allowed-headers: '*'
  mapping: /**
