spring:
  jpa:
    properties:
      hibernate:
        schema_update:
          unique_constraint_strategy: RECREATE_QUIETLY
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  datasource:
    password: 121586319ded898872dd33021fe19e3be9eda7534fb17b34328e3923fc84f852
    driver-class-name: org.postgresql.Driver
    username: xcigzwzzjpkpvw
    url: jdbc:postgresql://ec2-34-247-72-29.eu-west-1.compute.amazonaws.com:5432/dcf53027p75359
jwt:
  expiration-time: '1800000'
  secret: itransition
  type: Bearer
  header:
    name: json-web-token
  refresh:
    expiration-time: '10800000'
cors:
  allowed-origins: 'https://ilearning-task-4-client.herokuapp.com'
  allowed-methods: '*'
  allow-credentials: 'true'
  allowed-headers: '*'
  mapping: '/**'
